### ISSUE TITLE
Tá errado

### ISSUE THREAD

**Issue by filwaitman** [bertonha/chronosbot#1]
Tá errado pq tá.

**Comment by rochacon** [comment]
Não me parece certo também

**Comment by pedrospdc** [comment]
de acordo com minha chapeleta, tem muito pouca coisa correta nesse projeto, se tiver

**Comment by bertonha** [comment]
![image](https://github.com/bertonha/chronosbot/assets/1225902/e23fc490-37f0-42e1-9c35-60ea9771d0b8)

**Comment by pedrospdc** [comment]
> ![image](https://private-user-images.githubusercontent.com/1225902/296618717-e23fc490-37f0-42e1-9c35-60ea9771d0b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzA5OTQsIm5iZiI6MTcwNTI3MDY5NCwicGF0aCI6Ii8xMjI1OTAyLzI5NjYxODcxNy1lMjNmYzQ5MC0zN2YwLTQyZTEtOWMzNS02MGVhOTc3MWQwYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMjIxODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQyNzNkZGUzZTkxZDY5ZmI5YzA4ZWNhZGE5Y2YzN2M1YjllZmYzYjE3ZTdlYWI1NDBhYTE4YTFjMjdjMGQzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NT2NnLNhSPWlDCfGItT-hd8UVtOKvxfeJ84T__F6ivM)

ta errado, tinha que ser XL

**Comment by rochacon** [comment]
Pessoal, acho que consegui corrigir, é meu primeiro código em Rust, o patch ficou um pouco grande, seria bom ouvir a opinião de vocês no #2
